# name: MedicRecall2 Issue Report
# description: MedicRecall2 Main Issue Report Template
# title: "[Type of Issue]"
# projects: ["spe-upb/2024-MedicRecall2"]
# body:
#  - type: markdown
#     attributes:
#       value: |
#         Thank you for filling out an issue form for MedicRecall 2024
#   - type: dropdown
#     id: type
#     attributes:
#       label: Type of Issue
#       options:
#         - New Feature
#         - Enchancement/ Improvement
#         - Documentation
#         - Adhoc
#         - Bug
#       required: true
#       validation_message: Please select the type of issue      

#   - type: textarea
#     id: issue-description
#     attributes:
#       label: Is your feature request related to a problem? Please describe.
#       description: Please provide a description for the issue
#       placeholder: Describe the feature request in detail
#       validations:
#         required: true
      
#   - type: textarea
#     id: solution
#     attributes:
#       label: Describe the solution you'd like to add
#       description: Please provide a solution for the issue
#       placeholder: Describe the solution in detail
#       validations:
#         required: true

#   - type: textarea
#     id: additional_info
#     attributes:
#       label: Additional context
#       placeholder: Add any other context or screenshots about the feature request here
#       validations:
#         required: false

name: MedicRecall2 Issue Report
description: MedicRecall2 Main Issue Report Template
title: "[Type of Issue]"
projects: ["spe-upb/2024-MedicRecall2"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out an issue form for MedicRecall 2024
  - type: markdown
    attributes:
      value: |
        Please add all relevant issue metadata to your issue. This includes all relevant: assignees, labels, milestone and relevant branches/pull requests.  
  - type: checklist
    id: issue-type
    attributes:
      label: Type of Issue
      options:
        - label: New Feature
        - label: Enchancement/ Improvement
        - label: Documentation
        - label: Adhoc
        - label: Bug
        required: true
        validation_message: Please select the type of issue  
  - type: textarea
    id: issue-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Please provide a description for the issue
      placeholder: Describe the issue here.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Additional Information
      description: Please provide a solution for the issue
      placeholder: Describe the solution here
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Add any other context about the issue here.
      placeholder: Add any other context about the issue here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've linked this issue to a branch
        - label: I've add in the target date
        - label: I've added in the assignee (aka. the respective PIC)
        - label: I've set the priority and labels for this issue